# Generated by Django 2.1.2 on 2019-01-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
