# Generated by Django 2.1.7 on 2019-02-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20190119_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='qa/avatars/default.jpg', upload_to='qa/avatars/img_<django.db.models.fields.related.OneToOneField>.jpg'),
        ),
    ]
